name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: |
        npm ci
        npm install
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Set up Environment Variables
      run: |
        echo "CLOUD_API=${{ secrets.TEST_CLOUD_API }}" >> $GITHUB_ENV
        echo "AUTH_TOKEN=${{ secrets.TEST_AUTH_TOKEN }}" >> $GITHUB_ENV
        echo "NODE_PASSWORD=12345678" >> $GITHUB_ENV
        echo "NETWORK=regtest" >> $GITHUB_ENV
    - name: Run Playwright tests
      run: NODE_NAME=Node_A npx playwright test tests/api.node-run.test.ts
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30